### ISSUE TITLE
Can't add uptodown apps

### ISSUE THREAD

**Issue by jm355** [ImranR98/Obtainium#1956]
**Describe the bug**
uptodown links either get a warning toast saying it's an invalid url, or if I override the source it gives some kind of file error

**To Reproduce**
1. Attempt to add https://connect-iq-store.uptodown.com/android/descargar/ by pasting it in to the url field and tapping add
2. Select uptodown as the source ovverride
3. Tap add again

**Screenshots and Logs**
![Screenshot_20241108-061214](https://github.com/user-attachments/assets/ba44dc97-5692-49c9-a407-c4fe5e7f538b)
![Screenshot_20241108-061205](https://github.com/user-attachments/assets/b854c0fc-8fc9-4f3b-895a-7c2d6fca5971)

**Please complete the following information:**
 - Device: Pixel 8
 - OS: GrapheneOS
 - Obtainium Version: 1.1.29

**Additional context**
Also happens with https://garmin-explore.uptodown.com/android/descargar, https://symfonium.uptodown.com/android/descargar, and https://lovense-remote.uptodown.com/android/descargar

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.30

**Comment by jm355** [comment]
Thanks! I'm still getting this when I try to update though
![Screenshot_20241110-071329](https://github.com/user-attachments/assets/a46df915-f60a-4fca-9d86-0f17b27047a7)

**Comment by ImranR98** [comment]
This is a separate problem which I believe there is already an issue for. You could try "allow insecure requests" as a workaround but obviously that's not ideal.

**Comment by jm355** [comment]
I think this issue was caused by using the spanish version of the links. The english versions (see https://github.com/ImranR98/Obtainium/issues/1968) can at least download without any issue
