### ISSUE TITLE
Jump to battery setting when opening Obtainium in HyperOS2

### ISSUE THREAD

**Issue by LennoC** [ImranR98/Obtainium#2437]
**Describe the bug**
After upgrade to obtainium v1.2.1, it always jump to battery save setting when open EVERYTIME. I have to swipe back to obtainium screen.
I can open it normally in version v1.1.

**To Reproduce**
Just open obtainium v1.2.1, battery save setting page shows before normal screen.

**Screenshots and Logs**
logs
```
2025-07-30 08:41:43.653: info: 清除了 6 个日志（2025-07-23 08:41:43.621638 之前，null 之后）

2025-07-30 08:53:54.408: info: 已导入 1 个应用

2025-07-30 08:54:56.001: info: Installing "dev.imranr.obtainium" version "1.2.1" versionCode "23173"

2025-07-30 08:54:56.876: info: 当前版本

2025-07-30 08:56:37.919: info: Installing "dev.imranr.obtainium.fdroid" version "1.2.1" versionCode "23173" (from existing version "1.1.56" versionCode "23133")

2025-07-30 23:19:32.732: info: Installing "com.rosan.installer.x.revived" version "2.2.5" versionCode "38" (from existing version "2.2.4" versionCode "36")
```

Screenshot of battery save setting page

![Image](https://github.com/user-attachments/assets/4b4a30b4-cf9d-471e-b2ff-96d0bf935e94)

**Please complete the following information:**
 - Device: Xiaomi13
 - OS: HyperOS 2.0.203.0 stock
 - Obtainium Version: v1.2.1 release

**Additional context**

**Comment by DwainZwerg** [comment]
Just to be on the safe side: Have you already switched off battery optimization?

**Comment by LennoC** [comment]
No matter what I switch off battery optimization or not. The page shows
when open.

DwainZwerg ***@***.***> 于 2025年8月1日周五 02:21写道：

**Comment by ImranR98** [comment]
This is most likely due to the new "foreground service" setting -- it attempts to initialize a service even if you have turned that setting off (the service just remains unused but still "initialized"). This is fine on AOSP Android but I guess it causes problems on HyperOS. I'll try to change when the initialization happens, which should fix your issue (at least when "foreground service" is off).

**Comment by ImranR98** [comment]
It should be fixed now (if not we can re-open this issue).

**Comment by LennoC** [comment]
> It should be fixed now (if not we can re-open this issue).

Hi A pity. upgrade and test, the page still shows.
And I can't reopen the issues.

**Comment by scharmach** [comment]
> Just to be on the safe side: Have you already switched off battery optimization?

Thanks, had a similar issue (see below) and switching off battery optimization did the trick for me.

<img src="https://github.com/user-attachments/assets/490aa5e9-06d6-4abd-8327-5cbf788e5fb4" width="400" />

**Comment by LennoC** [comment]
After some versions, I can switch off the battery optimization of obtainium now.
issues closed.

**Comment by TigerBeanst** [comment]
@ImranR98 Sorry but I still got that pop-up

v1.2.9, on Xiaomi HyperOS 3 (Android 16)

https://github.com/user-attachments/assets/1cd50570-816e-477e-9fff-8a0d7933c5d2

**Comment by Everynevah** [comment]
Got the same issue, 
Newest obtainium. 
Prompts the battery page every time.
Xiaomi hyper os 3.0.3.0
Redmi note 13 pro.
