### ISSUE TITLE
Any way to mass import starred repos?

### ISSUE THREAD

**Issue by soni0212** [ImranR98/Obtainium#6]
I have 100+ repos and link them 1 at a time is a strenuous job..
Can you implement a 1-click import setting?

Thankyou for all the efforts man

**Comment by ImranR98** [comment]
Fortunately the GitHub API lets us get a user's [starred repos](https://api.github.com/users/imranr98/starred) without logging in, so this should be simple to add for users who don't make it private. The downside is that each URL would also have to be scraped before it can be added, to make sure it has APK releases, so adding a 100+ repos at once might still cause problems.

I'll look into it for the next release, but that may be a while.

**Comment by ImranR98** [comment]
Notes for reference later:
1. Create a `MassAppSource` astract class, which:
    - Is used to generate a list of App Source URLs to be added, from a "single source" - like a single user's GitHub stars
    - Declares a list of strings that it needs in order to do its work (for GitHub, this is only the username assuming their stars are public)
    - Declares a function which takes a list of arguments (assumed to be in the same order as the declared list above), extracts the URLs, and returns them (to then be added one at a time as described later)
2. Implement a `MassAppSource` for GitHub stars (the only one for now, more could be added in the future), call it `GitHubStars`
3. Add a 4th page to the bottom navbar - call it "Import/Export" - with several buttons, each of which opens a modal:
    - "Import from Obtainium Export" - existing import function
    - "Import from URL List"
        - Takes a plain user-provided list of links, each of which is added using the existing add function which validates the URL and gets APK details
        - If any link fails to be imported, the list of failures is presented (also in a modal) at the end (the rest go through)
    - One button for each `MassAppSource` ("Import from GitHub Stars", "Import from XYZ", etc.):
        - Asks the user for all info needed by that source (dynamically created form) and extracts a list of URLs
        - Then calls the same function used by "Import from URL List", passing in those URLs
    - "Obtainium Export" - existing export function - visually differentiated from the above buttons
4. Existing import/export button should of course be removed from the settings page

**Comment by ImranR98** [comment]
Added in the latest release.

**Comment by S7venLights** [comment]
Tested for the first time tоԁау, it seems to only find the same first 30 apps each time I search my github username. There are more than 30 apps starred.

**Comment by S7venLights** [comment]
soni0212 have you managed to import all ⭐ repos?

**Comment by ImranR98** [comment]
It's because of GitHub's API rate limit. We make 1 request to get the list of Apps, then we make 1 request for each App in order to figure out which ones have releases with APKs and should therefore be added (since not all the user's repos will be Android apps). I'm guessing it errors out after hitting the limit. Do you see any errors? It should show them in a dialog box.

There's no good way to bypass the rate limit, so you would have to wait 30 minutes before trying again. Of course at that point, it would find the same first 30 Apps and time out again.

All I can do right now is add a check to avoid re-adding an App if it is already there, so the first 30 added Apps will be skipped and the next set can come in. You'll still have to wait 30 minutes each time but you will be able to add all the Apps eventually.

**Comment by S7venLights** [comment]
That's seems like the best solution yes.
I'm gonna test connecting via vpn or tor and see if that bypasses the rate limit each time I change my IP.

**Comment by S7venLights** [comment]
Rate limit does seem to be reaced pretty fast even with normal app use.
Maybe your same idea of checking the first 30 starred repos then the next 30 after 30 min, could also be applied to update checks.
So obtanium would check for updates in batches of 20 or 30, every hour or so.
That way when the user navigates the app they are less likely to be rate limited

Should work for most people. I have 80apps including default apps so maybe 50 that are github. So it will cover everything in 3 hours.

There could be an option for it in the 'Background update check interval'  settings.

**Comment by ImranR98** [comment]
Turns out that GitHub star imports have an additional problem on top of potential rate limits. The GitHub API itself only returns the user's first 30 stars by default, for example: https://api.github.com/users/S7venLights/starred
The least they could do is give some sort of warning that API results are incomplete 🤦

The maximum number of items you can get per page is 100, so we would need to keep making requests until we get to the last page with less than 100 results, for example: https://api.github.com/users/S7venLights/starred?per_page=100&page=2 
Will focus on the rate limit issue for now, and work on this after.

**Comment by S7venLights** [comment]
I wonder if the API can access all of github lists 🤔 That feature where you add apps to a list. 
That way one could make a list of all the apps they want to import.

**Comment by ImranR98** [comment]
Fixed in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.5.0-beta

**Comment by Philippe-Choquette** [comment]
> I couldn't find anything on lists, it's a newer feature so maybe no API yet. Definitely feel free to make an issue if you find anything.

It's still not implemented By GitHub but there's been an open discussion about it for some time, with the suggestion added internally as feedback:
https://github.com/orgs/community/discussions/8293?sort=new

Being able to import lists would also be useful for me
